In [1]:
import pandas as pd

In [2]:
df_s = pd.read_csv("tsx_eod_2025-06-26_seq.csv")

In [3]:
df_s.head()

  symbol        date    open   high     low  close  adjusted_close  volume
0    AAB  2025-06-26   0.035   0.04   0.035   0.04            0.04   23700
1   AAPL  2025-06-26  29.190  29.33  28.890  29.17           29.17  230686
2   AAUC  2025-06-26  18.500  18.60  18.260  18.59           18.59  114134
3    AAV  2025-06-26  11.530  11.64  11.450  11.60           11.60  381999
4   ABRA  2025-06-26   4.620   4.95   4.600   4.92            4.92  224226

In [4]:
df_s.nunique()

symbol            764
date                1
open              655
high              674
low               677
close             651
adjusted_close    651
volume            708
dtype: int64

In [5]:
df_t = pd.read_csv("tsx_eod_2025-06-26_thread.csv")

In [6]:
df_t.head()

  symbol        date    open   high     low  close  adjusted_close   volume
0   AAPL  2025-06-26  29.190  29.33  28.890  29.17           29.17   230686
1    AAB  2025-06-26   0.035   0.04   0.035   0.04            0.04    23700
2   AAUC  2025-06-26  18.500  18.60  18.260  18.59           18.59   114134
3     AC  2025-06-26  19.870  20.50  19.810  20.49           20.49  3707671
4    ACD  2025-06-26   3.430   3.49   3.430   3.49            3.49      306

In [7]:
df_t.nunique()

symbol            764
date                1
open              655
high              674
low               677
close             651
adjusted_close    651
volume            708
dtype: int64